### ISSUE TITLE
3rd button click opens registration in the new tab instead of the article

### ISSUE THREAD

**Issue by KarolTrzeszczkowski** [honest-cash/honestcash#1]
When I click the tittle with the third mouse button (scroll wheel) i'd expect a page opening in a new tab but instead I get the starting page of honest.cash.
**Result:**
![zrzut ekranu](https://user-images.githubusercontent.com/11697819/48947412-644cf080-ef31-11e8-91e4-9a789bc4719e.png)
**Expected result:**
![zrzut ekranu](https://user-images.githubusercontent.com/11697819/48947430-6fa01c00-ef31-11e8-8fdb-5c5c873025d5.png)
**Browser console output:**
![zrzut ekranu](https://user-images.githubusercontent.com/11697819/48947437-77f85700-ef31-11e8-9e0c-bc720ad7b538.png)

Firefox 63.0.1 (64-bit)
Arch Linux 4.14.79-1-lts

**Comment by adrianbarwicki** [comment]
Thanks a lot for submitting the issue. We 'll try to fix it asap!

**Comment by adrianbarwicki** [comment]
The improvements have just been added.
