### ISSUE TITLE
Balance not updating

### ISSUE THREAD

**Issue by KarolTrzeszczkowski** [honest-cash/honestcash#16]
When I click my image from the main page and go to "connected wallet" I see 0BCH balance. Then I click on "Deposit" and the balance appears and stays when I go back to "wallet keys"
![zrzut ekranu](https://user-images.githubusercontent.com/11697819/49404281-51b39200-f74f-11e8-88d2-8b325017eb15.png)
![zrzut ekranu](https://user-images.githubusercontent.com/11697819/49404299-6132db00-f74f-11e8-838b-fe76a943988a.png)
Expected result:
Balance can be seen right away.

Firefox 63.0.1 (64-bit)
Arch Linux 4.14.79-1-lts

**Comment by adrianbarwicki** [comment]
Fixed. I did not test on Linux though. Can you double check?

**Comment by KarolTrzeszczkowski** [comment]
Yes, it works :+1:
