### ISSUE TITLE
[Editor] Inline toolbar does not show

### ISSUE THREAD

**Issue by BigBlockIfTrue** [honest-cash/honestcash#173]
In the post editor (v2), the inline toolbar (with bold, italic, insert link) never becomes visible. Selecting text does not help.

As a result, I am completely unable to format my text or insert links.

The problem presents itself in both Firefox and Chromium. I can see the inline toolbar in the browser’s dev console but it always has display none. The toolbar appears to be functional after I manually set it to display block and assign a position.

**Comment by nynevi** [comment]
Hello,

thank you for your report. I have tested the inline toolar in Chrome 75.0.3770.100, Chromium 77.0.3833.0 and Firefox 66.0.5 but I was not able to reproduce the issue.

we are talking about this toolbar right?
![gif](https://media.giphy.com/media/ifeZZd1HOwzF7jXdhD/giphy.gif)

it might be case specific issue relating to the steps taken during editing or the browser version. We use [EditorJS](https://editorjs.io/) as our editor so the bug probably stem from it as we have no specific CSS targeting that specific toolbar. Editorjs under the hood manages toggling of show classes so there might be a problem where editor does not pick up on which block (paragraph, image, embed etc) you are on thus not applying the focused (or show) classes

So to pinpoint the problem and fix it (or report to editorjs atleast), could you provide more details such as your browser and the version or even a gif would be appreciated on how to reproduce.

**Comment by BigBlockIfTrue** [comment]
Yes, that's the toolbar I mean. I do exactly what you do in your recording, except I never get to see that toolbar. No matter how I select text (drag or double-click), the toolbar never becomes visible for me.

I use Linux Mint 19.1 (Cinnamon 4.0.10), which is based on Ubuntu 18.04. I tried Firefox 67.0.4 ("Firefox for Linux Mint" 1.0) and Chromium 75.0.3770.90.

**Comment by BigBlockIfTrue** [comment]
Sadly, when manually making the toolbar visible via the dev console, the applied mark-up is not saved and thus lost on reloading the page (despite the autosave function detecting it as a change to the post).

**Comment by BigBlockIfTrue** [comment]
I also reproduced the issue on a Windows 7 machine with both Firefox and Chrome. But I see you have a fix underway in #174.
