### ISSUE TITLE
[Feature] Always show balance in the navbar

### ISSUE THREAD

**Issue by m4ktub** [honest-cash/honestcash#19]
With the possibility to tip, make uncensurable, and receive tips all over the site it would be useful to always have your balance be displayed. This way you could quickly confirm if you have enough balance or how much you will be left with after an upvote. For example, when your balance runs low, you may consider your upvotes more precious as an upvote in a mediocre content may prevent you from upvoting a really good post in the future.

Here's a UI suggestion where feedback for increments / decrements would be provided by green and red colors. A sound could also be played for increments, since decrements are associated with user actions and require not feedback on the wallet.

<img src="https://user-images.githubusercontent.com/253588/49528728-7a9d6980-f8ac-11e8-9db7-6f4b2ab2b434.png" width="400"/>

**Comment by adrianbarwicki** [comment]
Thanks a lot for the design. We have put it on our short-term todo list!

**Comment by nynevi** [comment]
@m4ktub with the PR #35 I hope it will somehow satisfy your needs. If you have any more feedback please do not hesitate to create an issue, we'd love to take a look. thanks again for your request.
