### ISSUE TITLE
When making post Uncensorable can't exit popup I need refresh the page

### ISSUE THREAD

**Issue by amadeobrands** [honest-cash/honestcash#22]
As a user I want to exit the conformation popup so that I can continue to browse the website after I make a post Uncensorable

<img width="912" alt="screen shot 2018-12-10 at 00 26 33" src="https://user-images.githubusercontent.com/6133031/49699933-96896e00-fc12-11e8-93ee-3b8e8658cd4a.png">

**Comment by Letsgetitons** [comment]
I think nothing here..

**Comment by adrianbarwicki** [comment]
Thanks a lot for reporting it! I added it to bugs list and will include the fix in the next release.

**Comment by adrianbarwicki** [comment]
Fixed & deployed. Thanks for submitting the issue again!
