### ISSUE TITLE
Unable to tip any posts on https://honest.cash/profile/dagur

### ISSUE THREAD

**Issue by ftrader** [honest-cash/honestcash#27]
This is a profile with posts that I want to upvote, but for any of its posts, when I click on the B 0.002 button, I get an "Error: Try again later" message and the button subsequently grays out.

My wallet has sufficient funds and I have been able to tip other posts in my feed.

The inability to tip within a profile does not seem limited to the 'dagur' profile. I visited another profile (BrianXV) to test and got the same result.

**Comment by adrianbarwicki** [comment]
Thanks a lot for reporting it! This happens when the author did not specify their tipping address. We will adjust the error message accordingly.

**Comment by nynevi** [comment]
@ftrader thank you for reporting this issue. As we are maturing we love your feedback in any subject regarding Honest Cash.

I've recently joined ranks of HC therefore I'll keep an eye on the issues here and do my best on handling them.

The PR #31 will solve this issue when it is deployed. Please keep an eye out for the changes:

- the following will be hidden for everyone: upvote button, upvotes section, uncensorable section
- the following will be visible only to readers: A notification that says "This author does not accept tips." if the author does not have a BTC address.

P.S. these authors that do not have a BTC address will automatically have a wallet created for them thus the problem will resolve itself upon the login of the author.

**Comment by adrianbarwicki** [comment]
Fixed.
