### ISSUE TITLE
I can post on honest.cash, but I cannot login from any other browser

### ISSUE THREAD

**Issue by MichaelTen** [honest-cash/honestcash#4]
I can post on honest.cash, but I cannot login from any other browser. 

I signed up for an honest.cash account. 

I was somehow able to login and post. however on every other browser it won't let me login:
"The access the the platform is currently limited. Your account has not been activated. Tweet us at @HonestCash for a personal invitation."

michaelten is my name on honest.cash
 
i tried tweeting you. i hope my account can be fixed so i can post there sometimes from more than just one browser.. thank you!!!

**Comment by MichaelTen** [comment]
https://honest.cash/profile/221

**Comment by adrianbarwicki** [comment]
Thanks a lot for the feedback! I have just resend you an activation for your account. You should be good to go now.
