### ISSUE TITLE
Hindi posts do not load correctly

### ISSUE THREAD

**Issue by m4ktub** [honest-cash/honestcash#41]
Some posts with Hindi title and content do not load correctly. Examples:
- https://honest.cash/oodeyaa/-1721
- https://honest.cash/oodeyaa/-1676

As you can see the permalink is missing the left part, normally containing the _normalized_ title. This is probably failing because the post's title has no latin characters.

**Comment by nynevi** [comment]
@m4ktub thank you for reporting this. we will check our internal slugifying method/package and work on it.

Thank you

**Comment by adrianbarwicki** [comment]
> Some posts with Hindi title and content do not load correctly. Examples:
> 
> * https://honest.cash/oodeyaa/-1721
> * https://honest.cash/oodeyaa/-1676
> 
> As you can see the permalink is missing the left part, normally containing the _normalized_ title. This is probably failing because the post's title has no latin characters.

The cause of the problem has been fixed.
Affected posts have been corrected:
* https://honest.cash/oodeyaa/1721
* https://honest.cash/oodeyaa/1676
