### ISSUE TITLE
My post isn't publishable.

### ISSUE THREAD

**Issue by zander** [honest-cash/honestcash#6]
I created a new post and have published it various times (getting a little feedback item saying its published) but it sticks in the drafts area, showing up again when I press "write" and not appearing on the site.

**Comment by adrianbarwicki** [comment]
We have just fixed it. It was a momentary problem because we were deploying new updates. Can you publish now?

**Comment by zander** [comment]
Yes, kinda.

Can you fix the DB to not make it a reply?

**Comment by zander** [comment]
Not sure if this should be a separate issue:
when I went to your post and intended to write a reply to it, I got into the editor with my draft post in there.

I would argue that you need multiple drafts to avoid this happening.

**Comment by zander** [comment]
Closing as this "my post isnt publishable" bug is fixed.
